sample_table: metadata/set1.tsv
adapters:
    PE: "refs/adapters_PE.fa"
    SE: "refs/adapters_SE.fa"    
flexbar:
    adapter-trim-end: "RIGHT"
    adapter-min-overlap: 7
    max-uncalled: 5
    min-read-length: 25
    qtrim: "TAIL"
    qtrim-format: "sanger"
    qtrim-threshold: 20
    zip-output: "GZ"
bt2idx: "refs/Bowtie2Index/hg38"
bowtie2:
    multi:
        k: 100
        very-sensitive-local: ""
        score-min: "L,0,1.6"
        X: 1200
    best:
        very-sensitive-local: ""
        score-min: "L,0,1.6"
        X: 1200
    default:
        sensitive: ""

herv_annotation: "refs/HERV_rmsk.hg38.v2.gtf"
herv_annotation_tsv: "refs/HERV_rmsk.hg38.v2.tsv"
telescope:
    inform:
        exp_tag: "inform"
        theta_prior: 200000
        max_iter: 200
        updated_sam: ""        

btidx: "refs/BowtieIndex/hg38"
bowtie:
    repenrich:
        m: 1
        sam: ""
        X: 1200
        chunkmbs: 512
    default:
        sam: ""
        X: 1200
        chunkmbs: 512    

repenrich_py: "scripts/RepEnrich-1.2/RepEnrich.py"
repenrich_setup_py: "scripts/RepEnrich-1.2/RepEnrich_setup.py"
repenrich_bed: "refs/RepEnrich.hg38/repenrich_LTR.bed"
repenrich_index: "refs/RepEnrich.hg38/index_LTR"

tetx_te_gtf: "refs/tetx/hg38_rmsk_TE.gtf"
tetx_gene_gtf: "refs/tetx/hg38_genes.gtf"
        
